#!/usr/bin/env bash
# toolchain.sh — resolve and verify HOW this project is built and examined.
#
#   bash scripts/toolchain.sh resolve   # detect, write factory/toolchain.env if absent
#   bash scripts/toolchain.sh check     # prove the declared commands actually run
#   bash scripts/toolchain.sh print     # print the resolved values, no writes
#
# Why this is a STATION and not a side effect of the work order:
#
# The exam board has to know where the held-out suite will live, because in a
# compiled project that path is a build-manifest fact (Package.swift names its
# test targets) and not a directory the factory can invent afterwards. Writing
# toolchain.env at the work order — which runs AFTER the exam board — meant a
# Swift project got exam instructions that said "python3 standard library only"
# and a seal that removed a directory the project does not use. Declaration has
# to precede the station that depends on it.
#
# `check` exists because a toolchain.env with a typo in it is worse than none:
# every task parks with a failure that looks like the worker's fault. Commands
# are run for real and the receipt is kept.

set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/status.sh
. "$HERE/lib/status.sh"
cd "$FACTORY_ROOT" || exit 1

MODE="${1:-resolve}"
# `check` runs twice with different standards. Pre-exam it validates the
# DECLARATION (dirs, nesting, tools). Post-exam it also requires the runner
# scripts the exam board was told to write.
STAGE="pre-exam"
ENVFILE="factory/toolchain.env"

log() { printf '[toolchain] %s\n' "$*" >&2; }

# --- detection --------------------------------------------------------------

# detect_toolchain : echo one of swift|python|node|unknown, from what is on disk.
detect_toolchain() {
  if [ -f Package.swift ] || ls -d ./*.xcodeproj ./*.xcworkspace >/dev/null 2>&1; then
    printf 'swift'; return
  fi
  if [ -f pyproject.toml ] || [ -f requirements.txt ] || [ -f setup.py ]; then
    printf 'python'; return
  fi
  if [ -f package.json ]; then printf 'node'; return; fi
  printf 'unknown'
}

# write_profile <kind> : emit a starter toolchain.env for a detected kind.
# Values are the SAME defaults the exam board and the seal will be told, so
# there is one answer to "where are the held-out tests".
write_profile() {
  local kind="$1"
  case "$kind" in
  swift)
    cat > "$ENVFILE" <<'ENV'
# factory/toolchain.env — generated by scripts/toolchain.sh (detected: Swift)
#
# Where the suites live. HELDOUT_DIR is the load-bearing line: the seal, CI's
# tarball and scope check, runner.sh, inspect.sh and foreman/contracts.py all
# read it through scripts/lib/toolchain.sh. If it is wrong, the builder can read
# the exam while every log claims it cannot.
HELDOUT_DIR='Tests/HeldoutTests'
VISIBLE_DIR='Tests/VisibleTests'

VISIBLE_CMD='swift test --filter VisibleTests'
# --manifest-cache none is NOT optional: Package.swift declares the held-out
# target only when its directory exists, and SwiftPM caches the evaluated
# manifest by CONTENT, so without the flag a run can reuse a manifest evaluated
# in the other seal state and report "Executed 0 tests" as a pass.
HELDOUT_CMD='swift test --manifest-cache none --filter HeldoutTests'
BUILD_CMD='swift build'
EXTRA_GATE_CMD=''
FACTORY_ROLE_TIMEOUT=5400
ENV
    ;;
  node)
    cat > "$ENVFILE" <<'ENV'
# factory/toolchain.env — generated by scripts/toolchain.sh (detected: node)
HELDOUT_DIR='tests/heldout'
VISIBLE_DIR='tests/visible'
VISIBLE_CMD='npx --no-install jest tests/visible --passWithNoTests'
HELDOUT_CMD='npx --no-install jest tests/heldout'
BUILD_CMD='npm run build --if-present'
EXTRA_GATE_CMD=''
FACTORY_ROLE_TIMEOUT=1800
ENV
    ;;
  python|*)
    cat > "$ENVFILE" <<'ENV'
# factory/toolchain.env — generated by scripts/toolchain.sh
#
# Empty VISIBLE_CMD/HELDOUT_CMD means "use the runner scripts the exam board
# writes" (factory/tests/run-visible.sh, run-heldout.sh). That is the original
# Bodega default and it is what a stdlib-only Python project wants.
HELDOUT_DIR='factory/tests/heldout'
VISIBLE_DIR='factory/tests/visible'
VISIBLE_CMD=''
HELDOUT_CMD=''
BUILD_CMD=''
EXTRA_GATE_CMD=''
FACTORY_ROLE_TIMEOUT=3600
ENV
    ;;
  esac
}

# --- resolve ----------------------------------------------------------------

resolved_kind=""

# ensure_gitignore_entries <path>... : record working-tree artifacts that must
# never be committed.
#
# Idempotent, and it never rewrites a line that is already there.
#
# Deliberately NOT the held-out directory. The exam is tracked on purpose until
# the human moves it into the HELDOUT_TESTS secret — bootstrap's commit step
# carries it, and that copy is the only one that exists before the push. The
# README's `echo "$HELDOUT_DIR/" >> .gitignore` belongs AFTER the secret exists,
# so resolve only says so instead of doing it and silently orphaning the exam.
ensure_gitignore_entries() {
  local entry
  for entry in "$@"; do
    [ -n "$entry" ] || continue
    if [ -f .gitignore ]; then
      grep -qxF "$entry" .gitignore 2>/dev/null && continue
    fi
    printf '%s\n' "$entry" >> .gitignore 2>/dev/null \
      || { log "could not write .gitignore — add '$entry' by hand"; continue; }
    log ".gitignore: + $entry"
  done
}

do_resolve() {
  local kind; kind="$(detect_toolchain)"
  resolved_kind="$kind"
  if [ -f "$ENVFILE" ]; then
    log "$ENVFILE already exists — respecting the project's declaration (detected: $kind)"
  else
    mkdir -p factory
    write_profile "$kind"
    log "wrote $ENVFILE for a detected '$kind' project"
  fi
  # Make sure the directory the seal will remove actually exists, so the seal
  # test is meaningful rather than vacuously true on an empty path.
  # shellcheck disable=SC1090
  . "$HERE/lib/toolchain.sh"
  mkdir -p "$HELDOUT_DIR" "$VISIBLE_DIR" 2>/dev/null
  [ -f "$HELDOUT_DIR/.gitkeep" ] || : > "$HELDOUT_DIR/.gitkeep"
  # The sealed sandbox is a nested git worktree. Left visible and untracked, the
  # loop's salvage path `git add -A`s it as a mode-160000 gitlink — a project
  # inside the project, with no submodule config to explain it.
  ensure_gitignore_entries ".foreman-sandbox/" ".omp/"
  log "when the exam moves into the HELDOUT_TESTS secret, also run:"
  log "  git rm -r --cached '$HELDOUT_DIR' && echo '$HELDOUT_DIR/' >> .gitignore"
  log "heldout dir: $HELDOUT_DIR   visible cmd: ${VISIBLE_CMD:-<runner script>}"
  log "heldout cmd: ${HELDOUT_CMD:-<runner script>}"
}

# --- check ------------------------------------------------------------------
# Prove the declaration is real. Each command must be *runnable*: a command that
# is missing its tool fails here with the tool named, not at 3am inside a task.
do_check() {
  local fail=0
  # the stage arrives as $1 here (the case block passes "$2" of the script)
  STAGE="${1:-$STAGE}"
  # shellcheck disable=SC1090
  . "$HERE/lib/toolchain.sh"
  log "declared: $([ -f "$TOOLCHAIN_ENV" ] && echo yes || echo 'no — using defaults')"
  log "HELDOUT_DIR=$HELDOUT_DIR"

  local var cmd exe
  for var in BUILD_CMD VISIBLE_CMD HELDOUT_CMD; do
    cmd="$(eval printf '%s' \"\$$var\")"
    [ -n "$cmd" ] || { log "$var empty — falls back to the exam board's runner script"; continue; }
    exe="$(printf '%s' "$cmd" | awk '{print $1}')"
    # A runner-script fallback is checked by EXISTENCE — and its absence is only
    # an advisory here. This stage runs BEFORE the exam board, and those scripts
    # are the exam board's output: failing on a missing run-visible.sh at resolve
    # time would stop every Python project before it ever got to the station that
    # writes the file. exam_gate is what proves the runners exist and are red.
    case "$cmd" in bash\ factory/tests/*)
      f="${cmd#bash }"
      if [ -f "$f" ]; then
        ok "$var runs $f"
      elif [ "$STAGE" = "post-exam" ]; then
        log "MISSING $var targets $f — the exam board never wrote it"; fail=1
      else
        log "$var targets $f, which the exam board has not written yet (expected pre-exam)"
      fi
      continue ;;
    esac
    if command -v "$exe" >/dev/null 2>&1; then
      ok "$var uses $exe ($(command -v "$exe"))"
    else
      log "MISSING TOOL: $var='$cmd' but '$exe' is not on PATH"; fail=1
    fi
  done

  # The seal must be able to reach the directory it is told to remove.
  if [ -d "$HELDOUT_DIR" ]; then ok "HELDOUT_DIR exists ($HELDOUT_DIR)"
  else log "HELDOUT_DIR does not exist: $HELDOUT_DIR — the seal would be vacuous"; fail=1; fi

  # A declared held-out path that is a prefix of, or inside, the visible path
  # means sealing removes the visible suite too.
  case "$VISIBLE_DIR" in
    "$HELDOUT_DIR"|"$HELDOUT_DIR"/*)
      log "VISIBLE_DIR ($VISIBLE_DIR) is inside HELDOUT_DIR — sealing would delete the visible suite"; fail=1 ;;
  esac
  case "$HELDOUT_DIR" in
    "$VISIBLE_DIR"|"$VISIBLE_DIR"/*)
      log "HELDOUT_DIR ($HELDOUT_DIR) is inside VISIBLE_DIR — the seal would leak"; fail=1 ;;
  esac

  if [ "$fail" = 0 ]; then
    status_emit "toolchain" "-" "DONE" "toolchain resolved and verified (${HELDOUT_DIR})"
    return 0
  fi
  status_emit "toolchain" "-" "BLOCKED" "toolchain.env declares something that cannot run"
  return 1
}

ok() { printf '[toolchain]   ✓ %s\n' "$1" >&2; }

case "$MODE" in
  resolve) do_resolve; status_emit "toolchain" "-" "DONE" "resolved ${resolved_kind}" ;;
  check)   do_check "${2:-}" ;;
  kind)    detect_toolchain; echo ;;
  ci-matrix)
    # Emit the JSON a GitHub Actions matrix needs, so CI picks its runner from
    # the PROJECT's toolchain instead of assuming python3 on ubuntu. This is the
    # same detection the local pipeline uses — one answer, two consumers.
    kind="$(detect_toolchain)"
    case "$kind" in
      swift) runner="macos-14"; setup="swift" ;;
      node)  runner="ubuntu-latest"; setup="node" ;;
      *)     runner="ubuntu-latest"; setup="python" ;;
    esac
    printf '{"runner":"%s","setup":"%s","kind":"%s"}\n' "$runner" "$setup" "$kind" ;;
  get)
    # Print ONE resolved value. CI and foreman/tests call this so there is a
    # single parser for the project's profile; the Python reader in
    # foreman/contracts.py is checked against it by selftest (they must agree).
    . "$HERE/lib/toolchain.sh"
    key="${2:-}"
    case "$key" in
      HELDOUT_DIR|VISIBLE_DIR|VISIBLE_CMD|HELDOUT_CMD|BUILD_CMD|EXTRA_GATE_CMD|FACTORY_ROLE_TIMEOUT)
        # Indirect expansion, not eval: the list above is the allowlist, and a
        # value must never be executed just because someone asked to print it.
        printf '%s' "${!key:-}" ;;
      *) echo "get: refusing to print '$key' (not a toolchain key)" >&2; exit 2 ;;
    esac ;;
  print)   . "$HERE/lib/toolchain.sh"
           printf 'HELDOUT_DIR=%s\nVISIBLE_DIR=%s\nVISIBLE_CMD=%s\nHELDOUT_CMD=%s\nBUILD_CMD=%s\n' \
             "$HELDOUT_DIR" "$VISIBLE_DIR" "$VISIBLE_CMD" "$HELDOUT_CMD" "$BUILD_CMD" ;;
  --help|-h) sed -n '2,20p' "$0" | sed 's/^# \{0,1\}//' ;;
  *) echo "unknown mode: $MODE (want resolve|check [pre-exam|post-exam]|print|get|kind|ci-matrix)" >&2; exit 2 ;;
esac
